### PR TITLE
zip codes & po box

### PR DESCRIPTION
**Pull request by 8enmann**
#24 fix

### CODE REVIEW

**Comment by madisonmay** [comment]
Hi there!  Thanks for the contribution.  Would you also mind adding a few test cases to test.py (simly in the project root at the moment)?  Think we can get this addition merged in pretty expediently.

**Comment by 8enmann** [comment]
Working on it now!

**Comment by 8enmann** [comment]
Done

**Comment by madisonmay** [comment]
Great stuff.  A few final things I want to address before merge.  This library is designed with the intent of being high precision, low recall -- meaning that there is a bias towards missing potential matches rather than returning false matches.  I'm a bit worried that the zip code regex will often trigger on things other than zip codes (Any number greater than 5 digits, mainly).  This means that a regex for a zip code is a good option for a user that intends to pick out all possible zip codes, bu\ will likely return many matches that are not actually zip codes?  Thoughts?  

The P.O. box addition looks straightforward and good to go.

**Comment by 8enmann** [comment]
Good point. Added extra word boundary to zip code regex and a test.

**Comment by madisonmay** [comment]
Thanks for the update, merging.

**Pull request merged**
